# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SnapKit'
pod 'StarWars'
pod 'APESuperHUD'
pod 'JSAnimatedImagesView'

pod 'YYWebImage'

target 'JY-EyepetizerApp' do

end

