source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!

target "JYNews" do
pod "SnapKit", "~> 0.22.0”
pod "Kingfisher", "~> 2.x"
pod "SVProgressHUD"
pod "FDFullscreenPopGesture", "~> 1.1"
pod "Alamofire", "~> 3.x”
pod "SwiftyJSON"
pod "MJRefresh"

end
