# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Alamofire', '~> 3.0.0'
pod 'Kingfisher', '~> 2.6.0'

target 'JYHTMLSimpleProject' do

end

